const mongoose = require("mongoose");
const { Scholarship } = require("./App/model/scholarshipmodel");
require("dotenv").config();

const SCHOLARSHIPS = [
  { title: "National Means-cum-Merit Scholarship (NMMS)", provider: "Ministry of Education", amount: "₹12,000", amountValue: 12000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-09-30"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government"] },
  { title: "Post Matric Scholarship for SC Students", provider: "Ministry of Social Justice", amount: "₹1,20,000", amountValue: 120000, currency: "INR", eligibility: { categories: ["SC"], locations: ["India"], courses: ["Engineering","Medical","Law","Any"] }, deadline: new Date("2025-10-31"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government","SC"] },
  { title: "Post Matric Scholarship for ST Students", provider: "Ministry of Tribal Affairs", amount: "₹1,20,000", amountValue: 120000, currency: "INR", eligibility: { categories: ["ST"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-10-31"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government","ST"] },
  { title: "Post Matric Scholarship for OBC Students", provider: "Ministry of Social Justice", amount: "₹60,000", amountValue: 60000, currency: "INR", eligibility: { categories: ["OBC"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-10-31"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government","OBC"] },
  { title: "Central Sector Scheme of Scholarship for College Students", provider: "Ministry of Education", amount: "₹20,000", amountValue: 20000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-11-30"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government","merit"] },
  { title: "Prime Minister Scholarship Scheme for CAPF", provider: "Ministry of Home Affairs", amount: "₹36,000", amountValue: 36000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST"], locations: ["India"], courses: ["Engineering","Medical","Management","Any"] }, deadline: new Date("2025-10-15"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government","defence"] },
  { title: "Ishan Uday Scholarship for North East", provider: "University Grants Commission", amount: "₹54,000", amountValue: 54000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST"], locations: ["Assam","Arunachal Pradesh","Manipur","Meghalaya","Mizoram","Nagaland","Sikkim","Tripura"], courses: ["Engineering","Science","Arts","Commerce","Any"] }, deadline: new Date("2025-09-15"), url: "https://www.ugc.ac.in/ishan/", source: "ugc", tags: ["india","north-east","UGC"] },
  { title: "Begum Hazrat Mahal National Scholarship", provider: "Maulana Azad Education Foundation", amount: "₹12,000", amountValue: 12000, currency: "INR", eligibility: { categories: ["OBC","EWS"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-09-30"), url: "https://maef.nic.in", source: "maef", tags: ["india","government","minority","girls"] },
  { title: "Swami Vivekananda Merit-cum-Means Scholarship (WB)", provider: "West Bengal Government", amount: "₹60,000", amountValue: 60000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST"], locations: ["West Bengal"], courses: ["Engineering","Science","Arts","Commerce"] }, deadline: new Date("2025-12-31"), url: "https://svmcm.wbhed.gov.in", source: "wb_gov", tags: ["india","west-bengal","state"] },
  { title: "Mukhyamantri Medhavi Vidyarthi Yojana (MP)", provider: "Madhya Pradesh Government", amount: "₹1,50,000", amountValue: 150000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["Madhya Pradesh"], courses: ["Engineering","Medical","Any"] }, deadline: new Date("2025-11-30"), url: "https://scholarshipportal.mp.nic.in", source: "mp_gov", tags: ["india","state","merit"] },
  { title: "E-Grantz Scholarship (Kerala)", provider: "Kerala Government", amount: "₹25,000", amountValue: 25000, currency: "INR", eligibility: { categories: ["SC","ST","OBC","EWS"], locations: ["Kerala"], courses: ["Any"] }, deadline: new Date("2025-11-15"), url: "https://egrantz.kerala.gov.in", source: "kerala_gov", tags: ["india","kerala","state"] },
  { title: "Dr. Ambedkar Post Matric Scholarship for EBC Students", provider: "Ministry of Social Justice", amount: "₹80,000", amountValue: 80000, currency: "INR", eligibility: { categories: ["EWS"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-10-31"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government","EWS"] },
  { title: "National Fellowship for SC Students (NFSC)", provider: "University Grants Commission", amount: "₹2,22,000", amountValue: 222000, currency: "INR", eligibility: { categories: ["SC"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-12-15"), url: "https://www.ugc.ac.in", source: "ugc", tags: ["india","SC","fellowship"] },
  { title: "Tata Capital Pankh Scholarship", provider: "Tata Capital", amount: "₹50,000", amountValue: 50000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Engineering","Science","Arts","Commerce","Any"] }, deadline: new Date("2025-07-31"), url: "https://www.buddy4study.com/scholarship/tata-capital-pankh-scholarship-programme", source: "buddy4study", tags: ["india","private","tata"] },
  { title: "Reliance Foundation Undergraduate Scholarships", provider: "Reliance Foundation", amount: "₹2,00,000", amountValue: 200000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Engineering","Science","Arts","Commerce"] }, deadline: new Date("2025-12-31"), url: "https://scholarships.reliancefoundation.org", source: "reliance", tags: ["india","private"] },
  { title: "HDFC Bank Parivartan ECS Scholarship", provider: "HDFC Bank", amount: "₹75,000", amountValue: 75000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Engineering","Medical","Any"] }, deadline: new Date("2025-08-31"), url: "https://www.buddy4study.com/scholarship/hdfc-bank-parivartan-ecs-scholarship", source: "hdfc", tags: ["india","private","financial-need"] },
  { title: "Infosys Foundation Scholarship", provider: "Infosys Foundation", amount: "₹50,000", amountValue: 50000, currency: "INR", eligibility: { categories: ["SC","ST","OBC"], locations: ["India"], courses: ["Engineering","Science"] }, deadline: new Date("2025-09-30"), url: "https://www.infosys.com/infosys-foundation/", source: "infosys", tags: ["india","private","STEM"] },
  { title: "Sitaram Jindal Foundation Scholarship", provider: "Sitaram Jindal Foundation", amount: "₹36,000", amountValue: 36000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Engineering","Medical","Science","Arts","Commerce"] }, deadline: new Date("2025-10-31"), url: "https://www.sitaramjindalfoundation.org", source: "jindal", tags: ["india","private"] },
  { title: "Kotak Kanya Scholarship", provider: "Kotak Education Foundation", amount: "₹1,50,000", amountValue: 150000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Engineering","Medical","Science"] }, deadline: new Date("2025-08-15"), url: "https://www.buddy4study.com/scholarship/kotak-kanya-scholarship", source: "buddy4study", tags: ["india","private","girls"] },
  { title: "Aditya Birla Scholarships", provider: "Aditya Birla Group", amount: "₹65,000", amountValue: 65000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST"], locations: ["India"], courses: ["Engineering","Management","Science"] }, deadline: new Date("2025-09-30"), url: "https://www.adityabirlascholars.net", source: "aditya_birla", tags: ["india","private","merit"] },
  { title: "Vidyadhan Scholarship", provider: "Sarojini Damodaran Foundation", amount: "₹60,000", amountValue: 60000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Engineering","Medical","Science","Arts","Commerce"] }, deadline: new Date("2025-10-31"), url: "https://www.vidyadhan.org", source: "vidyadhan", tags: ["india","private","need-based"] },
  { title: "L'Oreal India For Young Women in Science", provider: "L'Oreal India", amount: "₹2,50,000", amountValue: 250000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Science","Engineering","Medical"] }, deadline: new Date("2025-11-30"), url: "https://www.loreal.com/en/india/articles/commitments/loreal-india-for-young-women-in-science-scholarships/", source: "loreal", tags: ["india","private","women","STEM"] },
  { title: "National Scholarship for Persons with Disabilities", provider: "Dept. of Empowerment of PWD", amount: "₹40,000", amountValue: 40000, currency: "INR", eligibility: { categories: ["GEN","SC","ST","OBC"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-11-30"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government","PWD"] },
  { title: "Post-Matric Scholarship for Students with Disabilities", provider: "Ministry of Social Justice", amount: "₹1,10,000", amountValue: 110000, currency: "INR", eligibility: { categories: ["GEN","SC","ST","OBC","EWS"], locations: ["India"], courses: ["Engineering","Medical","Any"] }, deadline: new Date("2025-10-31"), url: "https://scholarships.gov.in", source: "nsp_india", tags: ["india","government","PWD"] },
  { title: "AICTE Pragati Scholarship for PWD Girls", provider: "AICTE", amount: "₹50,000", amountValue: 50000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST"], locations: ["India"], courses: ["Engineering","Technology"] }, deadline: new Date("2025-12-31"), url: "https://www.aicte-india.org/bureaus/rifd/pragati", source: "aicte", tags: ["india","government","PWD","girls"] },
  { title: "Vidyasaarathi PWD Scholarship", provider: "Vidyasaarathi", amount: "₹25,000", amountValue: 25000, currency: "INR", eligibility: { categories: ["GEN","OBC","SC","ST","EWS"], locations: ["India"], courses: ["Any"] }, deadline: new Date("2025-09-30"), url: "https://www.vidyasaarathi.co.in", source: "vidyasaarathi", tags: ["india","private","PWD"] },
  { title: "Gates Scholarship", provider: "Bill & Melinda Gates Foundation", amount: "$30,000", amountValue: 30000, currency: "USD", eligibility: { categories: ["GEN"], locations: ["USA"], courses: ["Any"] }, deadline: new Date("2025-09-15"), url: "https://www.thegatesscholarship.org", source: "fastweb", tags: ["usa","full-ride"] },
  { title: "Coca-Cola Scholars Program", provider: "Coca-Cola Scholars Foundation", amount: "$20,000", amountValue: 20000, currency: "USD", eligibility: { categories: ["GEN"], locations: ["USA"], courses: ["Any"] }, deadline: new Date("2025-10-31"), url: "https://www.coca-colascholarsfoundation.org", source: "scholarships_com", tags: ["usa","leadership"] },
  { title: "Dell Scholars Program", provider: "Dell Foundation", amount: "$20,000", amountValue: 20000, currency: "USD", eligibility: { categories: ["GEN","EWS"], locations: ["USA"], courses: ["Any"] }, deadline: new Date("2025-12-01"), url: "https://www.dellscholars.org", source: "scholarships_com", tags: ["usa","need-based"] },
  { title: "Society of Women Engineers Scholarship", provider: "SWE", amount: "$16,000", amountValue: 16000, currency: "USD", eligibility: { categories: ["GEN"], locations: ["USA"], courses: ["Engineering","Science","Technology"] }, deadline: new Date("2025-12-31"), url: "https://scholarships.swe.org", source: "scholarships_com", tags: ["usa","women","STEM"] },
  { title: "Ron Brown Scholar Program", provider: "CAP Charitable Foundation", amount: "$40,000", amountValue: 40000, currency: "USD", eligibility: { categories: ["GEN"], locations: ["USA"], courses: ["Any"] }, deadline: new Date("2026-01-09"), url: "https://www.ronbrown.org", source: "fastweb", tags: ["usa","full-ride","leadership"] },
  { title: "Burger King Scholars Program", provider: "BK McLamore Foundation", amount: "$25,000", amountValue: 25000, currency: "USD", eligibility: { categories: ["GEN"], locations: ["USA","Canada"], courses: ["Any"] }, deadline: new Date("2025-12-15"), url: "https://www.bkmclamorefoundation.org", source: "fastweb", tags: ["usa","canada"] },
  { title: "Google Generation Scholarship", provider: "Google", amount: "$10,000", amountValue: 10000, currency: "USD", eligibility: { categories: ["GEN"], locations: ["USA","Canada"], courses: ["Engineering","Science","Technology"] }, deadline: new Date("2025-12-01"), url: "https://buildyourfuture.withgoogle.com/scholarships", source: "scholarships_com", tags: ["usa","tech","google"] },
  { title: "Amazon Future Engineer Scholarship", provider: "Amazon", amount: "$40,000", amountValue: 40000, currency: "USD", eligibility: { categories: ["GEN"], locations: ["USA"], courses: ["Engineering","Technology","Science"] }, deadline: new Date("2025-11-15"), url: "https://www.amazonfutureengineer.com", source: "fastweb", tags: ["usa","tech","amazon"] },
  { title: "AFCEA STEM Scholarship", provider: "Armed Forces Comm. & Electronics Assoc.", amount: "$3,000", amountValue: 3000, currency: "USD", eligibility: { categories: ["GEN"], locations: ["USA"], courses: ["Engineering","Technology","Science"] }, deadline: new Date("2026-01-15"), url: "https://www.afcea.org/scholarships", source: "fastweb", tags: ["usa","STEM"] },
];

async function clearAndSeed() {
  try {
    await mongoose.connect(process.env.DBURL);
    console.log("Connected to MongoDB\n");
    const deleted = await Scholarship.deleteMany({ source: { $in: ["local_html","demo"] } });
    console.log(`Cleared ${deleted.deletedCount} fake entries\n`);
    let inserted = 0, skipped = 0;
    for (const s of SCHOLARSHIPS) {
      const exists = await Scholarship.findOne({ title: s.title });
      if (!exists) { await Scholarship.create({ ...s, scrapedAt: new Date() }); console.log(`  + ${s.title}`); inserted++; }
      else skipped++;
    }
    console.log(`\nInserted ${inserted} | Skipped ${skipped}`);
    console.log(`Total in DB: ${await Scholarship.countDocuments()}`);
    await mongoose.connection.close();
    process.exit(0);
  } catch (err) {
    console.error("Error:", err.message);
    process.exit(1);
  }
}

clearAndSeed();